name: SCSS to CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g sass

    - name: Compile SCSS to CSS
      run: sass styles.scss styles.css

    - name: Commit and push compiled CSS
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add styles.css
        git commit -m "Compiled SCSS to CSS"
        git push
